//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlX {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class XControls : global::System.Configuration.ApplicationSettingsBase {
        
        private static XControls defaultInstance = ((XControls)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new XControls())));
        
        public static XControls Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4278190335")]
        public uint xButton {
            get {
                return ((uint)(this["xButton"]));
            }
            set {
                this["xButton"] = value;
            }
        }
    }
}
